Repository Diary-SPO/vk-bot, pull requests merged in 2023-10, with the labels that each got.

#12 updates: use postgre
  .env.example
  README_dev.md
  bun.lockb
  create tables.txt
  package.json
  src/config/index.ts
  src/dblogic/auth.ts
  src/dblogic/login.ts
  src/dblogic/logout.ts
  src/dblogic/sql/index.ts
  src/dblogic/sql/query.ts
  src/init/connectdb.ts
  src/init/db.ts
  src/scenes/home/index.ts
  src/scenes/login/index.ts
  src/scenes/schedule/index.ts
  src/types/index.ts
Labels: updates

#15 13 feature функция для проверки env переменных
  src/api/fetcher.ts
  src/config/index.ts
  src/config/types.ts
  src/config/utils.ts
Labels: (•_•)

#16 Readme edit
  README.md
  README_ru.md
Labels: documentation

#18 feature: use postgre
  bun.lockb
  src/api/fetcher.ts
  src/api/types.ts
  src/config/index.ts
  src/dblogic/login.ts
  src/dblogic/sql/query.ts
  src/init/bot.ts
  src/scenes/home/index.ts
  src/scenes/index.ts
  src/scenes/login/index.ts
  src/types/context/CustomContext.ts
  src/types/database/index.ts
  src/types/index.ts
Labels: (•_•)
